name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Generate lists
        run: |
          go run . -count 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
